### ISSUE TITLE
Do not generate html in java, use jsp for that purpose

### ISSUE THREAD

**Issue by AlphaBeth** [LeTrongDat/Web-programming#1]
https://github.com/LeTrongDat/Web-programming/blob/2d6e5082e5ad2f3ef6904ae6abcc8b016ff6d35d/lab-2/src/main/webapp/entity/Query.java#L77-L86

**Comment by LeTrongDat** [comment]
https://github.com/LeTrongDat/Web-programming/commit/e3bf4886eaf1a8e15723c5bba5537b2d7415e607
This is the commit that solve this issue.
