### ISSUE TITLE
GET isn' restricted according to task

### ISSUE THREAD

**Issue by AlphaBeth** [LeTrongDat/Web-programming#2]
https://github.com/LeTrongDat/Web-programming/blob/429d8e3b634fb0e3a1a0bc297cea77f08a1cb5c7/lab-2/src/main/webapp/controller/ParamsController.java#L38-L40

**Comment by AlphaBeth** [comment]
You have to redirect to jsp page

**Comment by LeTrongDat** [comment]
https://github.com/LeTrongDat/Web-programming/commit/f02b7e23595ea76ec8f0b69c8ff7ced1318557ba
This is the commit that solve this issue.
