### ISSUE TITLE
JSP is for representation, not for logic

### ISSUE THREAD

**Issue by AlphaBeth** [LeTrongDat/Web-programming#3]
https://github.com/LeTrongDat/Web-programming/blob/429d8e3b634fb0e3a1a0bc297cea77f08a1cb5c7/lab-2/web/result.jsp#L6-L11

**Comment by LeTrongDat** [comment]
https://github.com/LeTrongDat/Web-programming/commit/2aa6a1463ae8396bed8fa2222692d572c0b92e8d 
This is the commit that solve this issue.
