### ISSUE TITLE
Send multiple radiuses

### ISSUE THREAD

**Issue by AlphaBeth** [LeTrongDat/Web-programming#4]

**Comment by LeTrongDat** [comment]
https://github.com/LeTrongDat/Web-programming/commit/576a79d68348314063948a8d7059a7e276ad5abb

**Comment by AlphaBeth** [comment]
Oops!
An error has occurred
Error message: 1

**Comment by LeTrongDat** [comment]
https://github.com/LeTrongDat/Web-programming/commit/9f20836e942242e1df14625b82c8aaf95c46a416
